completed changes to teach tab and added scratchrj connect
LLK/scratchjr-website pull request #305
Opened 2021-04-27 15:36 UTC by epolak01

### Resolves

_What Github issue does this resolve (please include link)? Please make sure that the PR title reflects what the PR will do, not what is changing.
Please do not submit PRs that are not associated with a Github issue, or that only partially implement an issue._

- Resolves #

### Proposed Changes

In the Teach tab, changes Curricula to Resources, and Assessments to ScratchJr Connect. In Resources,
adds introduction and changes the text at the top. In ScratchJr Connect, replaces previous content with 
a description of scratchjr connect website and links it with a button.

### Reason for Changes

To integrate scratchJr connect website.

### Test Coverage

_Please show how you have added tests to cover your changes, or provide the testing steps to verify the change. Screenshots that show the change are also helpful._

2021-04-27 15:57 UTC, chrisgarrity commented on src/views/teach/connect.jsx
> +const ConnectSection = () => (
New connect stuff - yay

2021-04-27 15:57 UTC, martinatan commented on src/views/teach/connect.jsx
> +const ConnectSection = () => (
Yes!

2021-05-04 16:19 UTC, chrisgarrity commented on package.json
> +    "lint": "^0.7.0"
Please remove this - eslint is already in the devDependencies, so this is unnecessary.

2021-05-11 15:51 UTC, chrisgarrity requested changes
One small wording update. Otherwise looks great! thank you

2021-05-11 15:51 UTC, chrisgarrity commented on src/views/teach/activities/home.jsx
> +            in any order you&apos;d like!
Add 
For more information and a brief introduction to ScratchJr see the Resources page
```suggestion
            in any order you&apos;d like! For more information and a brief introduction to ScratchJr see the <a href=" /teach/resources">Resources page</a>.
```
I added a static link for resources page - I don't remember if that's the right way to do it when using react-router - please fix if needed.

2021-05-17 16:50 UTC, merged

2021-05-17 16:51 UTC, chrisgarrity commented
@epolak01 @martinatan thank you!